### Numpy

It is widely used Python Library which is used for the Scientific Computation in Python. It is used to create the arrays and matrices, along with some collection of mathematical functions applies on this data structures.

In this we will study about the Numpy its arrays and matrices and vectorized operations

In [22]:
import numpy as np

#creating a 1-D array
arr = np.array([1,2,3,4])
print(arr, type(arr)) #type will tell the .ndarray which tells it is n-dimensional array

#shape of the array: tell the dimension of array
print(arr.shape)

#convert 1-D to 2-D array
arr1 = arr.reshape((1,4))
print(arr1, type(arr1))

[1 2 3 4] <class 'numpy.ndarray'>
(4,)
[[1 2 3 4]] <class 'numpy.ndarray'>


In [23]:
#creating a 2D array
arr2 = np.array([[1,2,3,4,5,6], [2,3,4,5,6,2]])
print(arr2, type(arr2))

#check the shape of arr2 
print(arr2.shape)

[[1 2 3 4 5 6]
 [2 3 4 5 6 2]] <class 'numpy.ndarray'>
(2, 6)


In [24]:
#If we want to create a numpy array, same like we do list(1,10,2), tuple(1,10,2)
arr = np.arange(0,10).reshape(10,1) #10 rows and 1 columns reshaping
print(arr)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [25]:
#Some functions that are present in numpy and are useful
np.ones((2,3)) #creating an array of 2 rows and 3 cols and all elements are 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#identity matrix
np.eye(4) #It will create 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#Attributes of Numpy arrays

arr = np.array([[1,2,3], [4,5,6]])

print("Array is: \n", arr)
print("The Shape of array: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size(No.of Elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array is: 
 [[1 2 3]
 [4 5 6]]
The Shape of array:  (2, 3)
Dimension:  2
Size(No.of Elements):  6
Data type:  int64
Item size (in bytes):  8


In [28]:
#Numpy vectorized operation 
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,6,7,8,8,5])

#Element Wise Addition
print("Addition: ", arr1 + arr2)

#Element Wise Subtraction 
print("Subtraction: ", arr1 - arr2)


#Element Wise Subtraction 
print("Multiplication: ", arr1 * arr2)


#Element Wise Division
print("Division: ", arr1/arr2)

Addition:  [ 5  8 10 12 13 11]
Subtraction:  [-3 -4 -4 -4 -3  1]
Multiplication:  [ 4 12 21 32 40 30]
Division:  [0.25       0.33333333 0.42857143 0.5        0.625      1.2       ]


In [29]:
# Universal Functions: Functions that are applied to every element of the array
arr1 = np.array([1,2,3,4])

print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


In [30]:
#Performing Array slicing and Indexing
arr1 = np.array([[1,2,3,4,5], [1,3,4,5,7], [1,4,5,6,6]])

print("Array: \n", arr1)
print(arr1.shape)

Array: 
 [[1 2 3 4 5]
 [1 3 4 5 7]
 [1 4 5 6 6]]
(3, 5)


In [31]:
arr1[0][2] #accessing the 1st row and 3 col element


np.int64(3)

In [32]:
arr1[1:,3:]

array([[5, 7],
       [6, 6]])

In [33]:
arr1[:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [34]:
arr1[1:,2:4]

array([[4, 5],
       [5, 6]])

In [35]:
#Modify array elements
arr1[0][0] = 100
print(arr1)

arr1[1:] = 100
print(arr1)

[[100   2   3   4   5]
 [  1   3   4   5   7]
 [  1   4   5   6   6]]
[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [36]:
#Statistical Concepts- Normalization
data = np.array([1,2,3,4])

#to have the mean of 0 and standard deviation of 1
mean = np.mean(data)
std_dev = np.std(data) 

#Normalize the data 
normalized_data = (data - mean) / std_dev
print("Normalized Data: ", normalized_data, type(normalized_data))

Normalized Data:  [-1.34164079 -0.4472136   0.4472136   1.34164079] <class 'numpy.ndarray'>


In [37]:
#Performing Statistical Operation in Numpy
data = np.array([1,2,3,4])

mean = np.mean(data)
print("Mean: ", mean)

std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

median = np.median(data)
print("Median: ", median)

variance = np.var(data)
print("Variance: ", variance)

Mean:  2.5
Standard Deviation:  1.118033988749895
Median:  2.5
Variance:  1.25


In [38]:
#Logical Operation
arr1 = np.array([1,2,4,5,5,6,8,9])

arr1[(arr1>4) & (arr1<8)]

array([5, 5, 6])