### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np
array = np.random.randint(1,21, size=(5,5))
print("This is the Original Array: ")
print(array)

print()

array[:,2] = 1
print("Modified Array is: ")
print(array)

This is the Original Array: 
[[16 19 10  4  9]
 [18 18 11  4 12]
 [10 10 12  8  7]
 [15  6  3  4 17]
 [ 7 17  6 14  8]]

Modified Array is: 
[[16 19  1  4  9]
 [18 18  1  4 12]
 [10 10  1  8  7]
 [15  6  1  4 17]
 [ 7 17  1 14  8]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
array = np.arange(1,17).reshape((4,4))
print(array)

#Replace the diagonal elements with 0: use fill_diagonal
np.fill_diagonal(array, 0)
print("Modified Array is: ")
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array is: 
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
arr = np.arange(1,37).reshape(6,6)
print("Original Array is: ")
print(arr)

print("Subarray is: ")
print(arr[2:5, 1:4])

Original Array is: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Subarray is: 
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr = np.random.randint(1,21, size=(5,5))
print("Original Array: ")
print(arr)

#np.concatenate is used to convert into the single 1D array
border_ele = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print(border_ele)

Original Array: 
[[ 8  9  5 10  8]
 [13  9 20 16 18]
 [ 8 12  2  8 19]
 [18 15  9 13 12]
 [10 19  4 10 10]]
[ 8  9  5 10  8 10 19  4 10 10 13  8 18 18 19 12]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [6]:
arr1 = np.random.randint(1, 21, size=(3,4))
arr2 = np.random.randint(1, 21, size=(3,4))

print("First Array: ")
print(arr1)
print("Second Array: ")
print(arr2)

print("Addition: \n", arr1 + arr2)
print("Subtraction: \n", arr1 - arr2)
print("Multiplication: \n", arr1 * arr2)
print("Division: \n", arr1 / arr2)

First Array: 
[[17 19 18  6]
 [15  9 13 17]
 [17 14 13  4]]
Second Array: 
[[ 7 12 19  6]
 [13  3 15  8]
 [11 18  1 13]]
Addition: 
 [[24 31 37 12]
 [28 12 28 25]
 [28 32 14 17]]
Subtraction: 
 [[10  7 -1  0]
 [ 2  6 -2  9]
 [ 6 -4 12 -9]]
Multiplication: 
 [[119 228 342  36]
 [195  27 195 136]
 [187 252  13  52]]
Division: 
 [[ 2.42857143  1.58333333  0.94736842  1.        ]
 [ 1.15384615  3.          0.86666667  2.125     ]
 [ 1.54545455  0.77777778 13.          0.30769231]]



2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [13]:
arr = np.arange(1,17).reshape(4,4)
print("Original Array: ")
print(arr)

row_sum = np.sum(arr, axis=1) #axis=1 refers to the row and provide you another 1D array containing sum of each row
col_sum = np.sum(arr, axis=0) #axis=0 refers to the col and provide you another 1D array containing sum of each col
print("Row wise sum of each row is: ", row_sum)
print("Column wise sum of each column is: ", col_sum)

Original Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum of each row is:  [10 26 42 58]
Column wise sum of each column is:  [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [19]:
arr = np.random.randint(1,11, size=(5,5))
print("Original Array is: ")
print(arr)

print("The mean of Array is: ", np.mean(arr))
print("The median of Array is: ", np.median(arr))
print("The standard deviation of Array is: ", np.std(arr))
print("The variance of the Array is: ", np.var(arr))

Original Array is: 
[[ 7  7  7  4  5]
 [ 7  4  1  1  6]
 [10  1  5  8  8]
 [ 8  2  1  3  3]
 [ 7  4 10  3 10]]
The mean of Array is:  5.28
The median of Array is:  5.0
The standard deviation of Array is:  2.8916431315084505
The variance of the Array is:  8.3616


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [25]:
arr = np.arange(1,10).reshape(3,3)
print("Original Array is: ")
print(arr)

mean_arr = np.mean(arr)
std_arr = np.std(arr)

#The normalization of array
normalized_arr = (arr - mean_arr) / std_arr
print("The normalized array is: \n", normalized_arr)

Original Array is: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The normalized array is: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [40]:
#Automatically expanding smaller arrays so arithmetic operations can work between different shapes.

arr1 = np.random.randint(1,11, size=(3,3))
arr_add_each_row = np.random.randint(1,11, size=(3,))
print("The arr1 is: \n", arr1)
print("The arr2 is: \n", arr_add_each_row)

result = arr1 + arr_add_each_row
print("The final resulted array is: ")
print(result)

The arr1 is: 
 [[4 9 4]
 [8 9 5]
 [6 8 3]]
The arr2 is: 
 [1 4 7]
The final resulted array is: 
[[ 5 13 11]
 [ 9 13 12]
 [ 7 12 10]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [83]:
arr1 = np.random.randint(1,11, size=(4,4))
arr_sub_each_col = np.random.randint(1,11, size=(4,))
print("The arr1 is: \n", arr1)
print("The arr2 is: \n", arr_sub_each_col)

result = arr1 - arr_sub_each_col[:, np.newaxis] #newaxis convert the (4,) into the (4,1) means 4 rows and 1 col 
print("The final resulted array is: ")
print(result)

The arr1 is: 
 [[ 9  4  7  4]
 [ 4  8  4 10]
 [ 6  4  3  7]
 [ 7  8  6  2]]
The arr2 is: 
 [10 10  9  4]
The final resulted array is: 
[[-1 -6 -3 -6]
 [-6 -2 -6  0]
 [-3 -5 -6 -2]
 [ 3  4  2 -2]]


### Assignment 6: Linear Algebra


1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [54]:
matrix = np.random.randint(1,11, size=(3,3))
print("Original Array: ")
print(matrix)

print("Determinant of Array: ", np.linalg.det(matrix))
print("Inverse of Array: ", np.linalg.inv(matrix))
print("Eigenvalues of Array: ", np.linalg.eigvals(matrix))

Original Array: 
[[2 1 3]
 [3 8 8]
 [6 8 9]]
Determinant of Array:  -34.99999999999998
Inverse of Array:  [[-0.22857143 -0.42857143  0.45714286]
 [-0.6         0.          0.2       ]
 [ 0.68571429  0.28571429 -0.37142857]]
Eigenvalues of Array:  [17.70200112  2.19766915 -0.89967027]



2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [58]:
matrix1 = np.random.randint(1,11, size=(2,3))
matrix2 = np.random.randint(1,11, size=(3,2))

print("Matrix Multiplication of matrix1 and matrix2: \n", np.dot(matrix1, matrix2)) #matrix1 @ matrix2 this also gives the matrix multiplication 

[[119  78]
 [ 90  56]]
Matrix Multiplication of matrix1 and matrix2: 
 [[119  78]
 [ 90  56]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [62]:
arr = np.arange(1,10).reshape(3,3)
print("Original Array: \n", arr)

print("First Time Reshape: \n", arr.reshape(1,9))
print("Second Time Reshape: \n", arr.reshape(9,1))

Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First Time Reshape: 
 [[1 2 3 4 5 6 7 8 9]]
Second Time Reshape: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [66]:
arr = np.random.randint(1,10, size=(5,5))
print("Original Array: \n", arr)

print("Flattened Array: \n", arr.flatten())

print("Reshape the flattened array: \n", arr.reshape(5,5))

Original Array: 
 [[4 6 3 9 5]
 [6 1 5 8 7]
 [3 2 1 2 3]
 [1 3 3 4 2]
 [3 9 8 8 6]]
Flattened Array: 
 [4 6 3 9 5 6 1 5 8 7 3 2 1 2 3 1 3 3 4 2 3 9 8 8 6]
Reshape the flattened array: 
 [[4 6 3 9 5]
 [6 1 5 8 7]
 [3 2 1 2 3]
 [1 3 3 4 2]
 [3 9 8 8 6]]




### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [69]:
arr = np.random.randint(1,10, size=(5,5))
print("Original Array: \n", arr)

corner_ele = arr[[0, 0, -1, -1],[0, -1, 0, -1]]
print("The corner elements of array are: ", corner_ele)

Original Array: 
 [[9 1 6 9 4]
 [6 2 5 2 6]
 [4 8 1 3 9]
 [7 1 7 6 6]
 [7 2 9 3 9]]
The corner elements of array are:  [9 4 7 9]



2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [72]:
arr = np.random.randint(1,21, size=(4,4))
print("Original Array: \n", arr)

arr[arr > 10] = 10
print("Modified array is: \n", arr)

Original Array: 
 [[ 1  6  3 17]
 [15  3 17 15]
 [16  6 13  5]
 [14 19 18 17]]
Modified array is: 
 [[ 1  6  3 10]
 [10  3 10 10]
 [10  6 10  5]
 [10 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [81]:
data_type = [('name', 'U20'), ('age', 'i4'), ('weight', 'f4')] #this is the custom datatype we have created where U20: string upto 20 chars, i4: int-4byte and f4: float-4byte
data = np.array([('subrat', 44, 74.4), ('raj', 25, 45.9), ('sohan', 24, 89.0)], dtype=data_type)
print(data)

sorted_data = np.sort(data, order='age')
print(sorted_data)

[('subrat', 44, 74.4) ('raj', 25, 45.9) ('sohan', 24, 89. )]
['subrat' 'raj' 'sohan']
[('sohan', 24, 89. ) ('raj', 25, 45.9) ('subrat', 44, 74.4)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [85]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1,2), (3,4), (7,8)], dtype=data_type)

print(data['x'])
print(data['y'])

#Important think to understand
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print(distances)

[1 3 7]
[2 4 8]
[[0.         2.82842712 8.48528137]
 [2.82842712 0.         5.65685425]
 [8.48528137 5.65685425 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [93]:
''' 
Masked Arrays: Masked arrays are arrays that may have missing or invalid entries. The masked array module provides a convenient way to handle such data. 
You can create a masked array by using the numpy.ma.masked_array function, which takes an array and a mask as input. The mask is a boolean array that indicates which entries are valid 
(False) and which are invalid (True).
'''

import numpy.ma as ma

arr = np.random.randint(1,21, size=(4,4))
print("Original Array: \n", arr)

masked_arr = ma.masked_array(arr, mask=arr > 10) # it will create a mask array and mask=arr>10 means those values are greater than 10 are masked means hidden/invisible
print("Masked Array: \n", masked_arr)

masked_sum = masked_arr.sum()
print("Sum of all unmasked elements: ", masked_sum)

Original Array: 
 [[14  2  3 15]
 [ 7 11  7  1]
 [19  1 12  5]
 [18 13  3  2]]
Masked Array: 
 [[-- 2 3 --]
 [7 -- 7 1]
 [-- 1 -- 5]
 [-- -- 3 2]]
Sum of all unmasked elements:  31


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
arr = np.random.randint(1,21, size=(3,3))
print("Original Array: \n", arr)

masked_arr = ma.masked_array(arr, mask=np.eye(3))
print("Masked Array: \n", masked_arr)

unmasked_mean = masked_arr.mean()
print("The mean of unmasked array: ", unmasked_mean)

masked_arr = masked_arr.filled(unmasked_mean) #If basically fill the unmasked values with the mean of masked values
print("The new masked arr: \n", masked_arr)

Original Array: 
 [[20  3 14]
 [11  3 18]
 [ 4  7  4]]
Masked Array: 
 [[-- 3 14]
 [11 -- 18]
 [4 7 --]]
The mean of unmasked array:  9.5
The new masked arr: 
 [[ 9  3 14]
 [11  9 18]
 [ 4  7  9]]
