# Module: Pandas Assignments
## Lesson: Pandas













































### Assignment 1: DataFrame Creation and Indexing


1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [2]:
import pandas as pd
import numpy as np 

arr = np.random.randint(1,11, size=(6,4))
print(arr)

#As we have created a arr of 6 rows and 4 col using numpy and now we will convert it into the dataframe 
df = pd.DataFrame(arr, columns=['A', 'B', 'C', 'D']) #we can explicitly provide the columns name
df

#Now we have to set the first column as index
df.set_index('A', inplace=True)
df

[[ 6  7 10  3]
 [10  5  9  3]
 [ 6  6  7  6]
 [ 1  8  5  7]
 [ 8  6  7  1]
 [ 6  7 10  7]]


B   C  D
A           
6   7  10  3
10  5   9  3
6   6   7  6
1   8   5  7
8   6   7  1
6   7  10  7

In [ ]:
#Shorthand way of doing above ques1
df = pd.DataFrame(np.random.randint(1,11, size=(6,4)), columns=['A', 'B', 'C', 'D'])
print("Printing the Original Dataframe")
print(df)

#Now we want to set the first column as index of df
df.set_index('A', inplace=True)
print("Modified Dataframe is: ")
df

Printing the Original Dataframe
    A  B  C  D
0   8  3  7  4
1   5  7  5  6
2   1  4  4  4
3   8  9  4  5
4   5  1  6  6
5  10  1  6  6
Modified Dataframe is: 


B  C  D
A          
8   3  7  4
5   7  5  6
1   4  4  4
8   9  4  5
5   1  6  6
10  1  6  6

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [3]:
df = pd.DataFrame(np.random.randint(1,11, size=(3,3)), columns=['A','B','C'], index=['X','Y','Z'])
print("The Original Dataframe is: ")
print(df)

#Accessing the element of specific column
print("The elements of Row Y and Column B is: ")
print(df.at['Y','B'])

The Original Dataframe is: 
   A   B  C
X  2  10  2
Y  2   8  7
Z  9  10  2
The elements of Row Y and Column B is: 
8


### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [43]:
df = pd.DataFrame(np.random.randint(1,11, size=(5,3)), columns=['A','B','C'])
print("The Original Dataframe is: ")
print(df)

df['D'] = df['A'] * df['B']
print("The modified dataframe is: ")
df

The Original Dataframe is: 
    A   B   C
0   9   1  10
1  10  10   4
2   8   4   8
3   1   9   7
4   7   1   5
The modified dataframe is: 


A   B   C    D
0   9   1  10    9
1  10  10   4  100
2   8   4   8   32
3   1   9   7    9
4   7   1   5    7

2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [ ]:
df = pd.DataFrame(np.random.randint(1,11, size=(4,3)), columns=['A','B','C'])
print("The Original Dataframe is: ")
print(df)

row_sum = df.sum(axis=1) #axis=1 tell to compute row wise sum
col_sum = df.sum(axis=0) #by-default it is col wise sum means axis=0
print("The row wise sum is:\n", row_sum)
print("The col wise sum is:\n", col_sum)

The Original Dataframe is: 
   A  B   C
0  7  5   4
1  6  1  10
2  8  5   7
3  8  4   8
The row wise sum is:
 0    16
1    17
2    20
3    20
dtype: int64
The col wise sum is:
 A    29
B    15
C    29
dtype: int64


### Assignment 3: Data Cleaning



1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [62]:
df = pd.DataFrame(np.random.randint(1,11, size=(5,3)), columns=['A','B','C'])
print("The Original Dataframe is: ")
print(df)

df.at[0,'A'] = np.nan
df.at[2,'B'] = np.nan
df.at[3,'C'] = np.nan
df.at[4,'B'] = np.nan

print("Dataframe after introducing the nan values: ")
print(df)

df.fillna(df.mean(), inplace=True) #It will fill the nan value with the mean of respective column
print("DataFrame with NaN values filled:")
df

The Original Dataframe is: 
   A  B   C
0  9  7   5
1  4  6   6
2  9  2  10
3  7  4   6
4  4  5   5
Dataframe after introducing the nan values: 
     A    B     C
0  NaN  7.0   5.0
1  4.0  6.0   6.0
2  9.0  NaN  10.0
3  7.0  4.0   NaN
4  4.0  NaN   5.0
DataFrame with NaN values filled:


A         B     C
0  6.0  7.000000   5.0
1  4.0  6.000000   6.0
2  9.0  5.666667  10.0
3  7.0  4.000000   6.5
4  4.0  5.666667   5.0

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [67]:
df = pd.DataFrame(np.random.randint(1,11, size=(6,4)), columns=['A','B','C','D'])
print("The Original Dataframe is: ")
print(df)

df.at[0,'A'] = np.nan
df.at[2,'B'] = np.nan
print("Dataframe after introducing the nan values")
print(df)

#drop the rows with nan values
df.dropna(inplace=True) #.drop() remove all the rows which have nan values, axis=1 drop the column with any nan values
print("Modified dataframe: ")
df

The Original Dataframe is: 
   A   B   C  D
0  1   2  10  8
1  8  10  10  3
2  2   5   6  7
3  4   9   3  1
4  6   9   3  5
5  1   7   3  3
Dataframe after introducing the nan values
     A     B   C  D
0  NaN   2.0  10  8
1  8.0  10.0  10  3
2  2.0   NaN   6  7
3  4.0   9.0   3  1
4  6.0   9.0   3  5
5  1.0   7.0   3  3
Modified dataframe: 


A     B   C  D
1  8.0  10.0  10  3
3  4.0   9.0   3  1
4  6.0   9.0   3  5
5  1.0   7.0   3  3

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [73]:
df = pd.DataFrame({'Category': np.random.choice(['A','B','C'], size=12), 'Value': np.random.randint(1,11, size=12)})
print("The Original Dataframe is")
print(df)

grouped_df = df.groupby('Category')['Value'].agg(['sum', 'mean'])
print("The mean and sum of each category value is: ")
print(grouped_df)

The Original Dataframe is
   Category  Value
0         A      2
1         B      9
2         A      4
3         A     10
4         B      7
5         A      1
6         A      2
7         A      2
8         B      8
9         C      3
10        B      9
11        B      9
The mean and sum of each category value is: 
          sum  mean
Category           
A          21   3.5
B          42   8.4
C           3   3.0


2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.


In [80]:
df = pd.DataFrame({'Product': np.random.choice(['Prod1', 'Prod2', 'Prod3'], size=10), 'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Sales': np.random.randint(1, 11, size=10)})
print("Original DataFrame:")
print(df)

total_sales = df.groupby('Category')['Sales'].sum()
print("The total sales for each category: ")
print(total_sales)

Original DataFrame:
  Product Category  Sales
0   Prod1        C      7
1   Prod1        B      6
2   Prod2        B      2
3   Prod1        A     10
4   Prod2        C      6
5   Prod2        C      9
6   Prod3        B      6
7   Prod1        A      2
8   Prod2        B      3
9   Prod2        C     10
The total sales for each category: 
Category
A    12
B    17
C    32
Name: Sales, dtype: int32



### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [93]:
df1 = pd.DataFrame({'Key': ['A','B','C','D'], 'Value1': np.random.randint(1,21, size=4)})
print("Original Dataframe df1 is: ")
print(df1)

df2 = pd.DataFrame({'Key': ['A','B','E','D'], 'Value2': np.random.randint(1,21, size=4)})
print("Original Dataframe df2 is: ")
print(df2)

merge = pd.merge(df1, df2, on="Key")

Original Dataframe df1 is: 
  Key  Value1
0   A      18
1   B      12
2   C      10
3   D       7
Original Dataframe df2 is: 
  Key  Value2
0   A       6
1   B       7
2   E       9
3   D       3


2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.


In [98]:
df1 = pd.DataFrame({'A': np.random.randint(1, 100, size=3), 'B': np.random.randint(1, 100, size=3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 100, size=3), 'D': np.random.randint(1, 100, size=3)})
print("DataFrame 1:")
print(df1)
print("DataFrame 2:")
print(df2)

#Concatenate
row_conc = pd.concat([df1,df2], axis=0)
print("The row concatenate of df1 and df2: ")
print(row_conc)

col_conc = pd.concat([df1,df2], axis=1)
print("The col concatenate of df1 and df2: ")
print(col_conc)

DataFrame 1:
    A   B
0  93  68
1  68  41
2  68  94
DataFrame 2:
    C   D
0   2  56
1  65  43
2  90  61
The row concatenate of df1 and df2: 
      A     B     C     D
0  93.0  68.0   NaN   NaN
1  68.0  41.0   NaN   NaN
2  68.0  94.0   NaN   NaN
0   NaN   NaN   2.0  56.0
1   NaN   NaN  65.0  43.0
2   NaN   NaN  90.0  61.0
The col concatenate of df1 and df2: 
    A   B   C   D
0  93  68   2  56
1  68  41  65  43
2  68  94  90  61


### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [131]:
date_range = pd.date_range(start="2025-01-01", end="2025-12-31", freq='D') #here D means Daily means every date from start and end will be considered
df = pd.DataFrame(date_range, columns=['Date'])
df['Values'] = np.random.randint(1,21, size=len(date_range))
df.set_index('Date', inplace=True)
print(df)

monthly_mean = df.resample('ME').mean()
print("Computing the mean of values for each month")
print(monthly_mean)


            Values
Date              
2025-01-01      20
2025-01-02       6
2025-01-03      13
2025-01-04       9
2025-01-05       6
...            ...
2025-12-27      10
2025-12-28      20
2025-12-29      17
2025-12-30      12
2025-12-31      14

[365 rows x 1 columns]
Computing the mean of values for each month
               Values
Date                 
2025-01-31   9.741935
2025-02-28  11.892857
2025-03-31   8.838710
2025-04-30   9.966667
2025-05-31   8.225806
2025-06-30   9.766667
2025-07-31  11.419355
2025-08-31   9.483871
2025-09-30   8.200000
2025-10-31   9.806452
2025-11-30   9.333333
2025-12-31  10.516129


2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [5]:
date_range = pd.date_range(start="2021-01-01", end="2021-12-31", freq='D') #here D means Daily means every date from start and end will be consider
df = pd.DataFrame(date_range, columns=['Date'])
df['Values'] = np.random.randint(1,21, size=len(date_range))
df.set_index('Date', inplace=True)
print(df)

rolling_mean = df.rolling(window=7).mean()
print("Computing the mean of values for every week(window of 7days) from start and end date")
print(rolling_mean)

            Values
Date              
2021-01-01       5
2021-01-02       4
2021-01-03      11
2021-01-04      12
2021-01-05       7
...            ...
2021-12-27      14
2021-12-28       3
2021-12-29       7
2021-12-30      15
2021-12-31      15

[365 rows x 1 columns]
Computing the mean of values for every week(window of 7days) from start and end date
               Values
Date                 
2021-01-01        NaN
2021-01-02        NaN
2021-01-03        NaN
2021-01-04        NaN
2021-01-05        NaN
...               ...
2021-12-27   8.142857
2021-12-28   7.142857
2021-12-29   7.285714
2021-12-30   8.857143
2021-12-31  10.714286

[365 rows x 1 columns]


### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [20]:
array = [['A','A','B','B'], ['one','two','one','two']]
index = pd.MultiIndex.from_arrays(array, names=('Category','Sub-Category'))
df = pd.DataFrame(np.random.randint(1,21, size=(4,3)), index=index, columns=['Value1','Value2','Value3'])
print(df)

#Performing the Operations: Indexing
print("Indexing")
print(df.loc['A'])

print()

#Slicing
print("Slicing")
print(df.loc[('B','two')])

                       Value1  Value2  Value3
Category Sub-Category                        
A        one               10      12      12
         two                3      18      20
B        one               10      18       1
         two               15       8       3
Indexing
              Value1  Value2  Value3
Sub-Category                        
one               10      12      12
two                3      18      20

Slicing
Value1    15
Value2     8
Value3     3
Name: (B, two), dtype: int32


2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [27]:
array = [['A','A','B','B'], ['one','two','one','two']]
index = pd.MultiIndex.from_arrays(array, names=('Category','Sub-Category'))
df = pd.DataFrame(np.random.randint(1,21, size=(4,3)), index=index, columns=['Value1','Value2','Value3'])
print(df)

print("The sum of values(value1, value2 and value3) for each category: ")
sum_values1 = df.groupby('Category').sum()
print(sum_values1)

print("The sum of values(value1, value2 and value3) for each subcategory: ")
sum_values2 = df.groupby('Sub-Category').sum()
print(sum_values2)

                       Value1  Value2  Value3
Category Sub-Category                        
A        one                1      12       5
         two                3      20       7
B        one               16       4      16
         two               18      20      17
The sum of values(value1, value2 and value3) for each category: 
          Value1  Value2  Value3
Category                        
A              4      32      12
B             34      24      33
The sum of values(value1, value2 and value3) for each subcategory: 
              Value1  Value2  Value3
Sub-Category                        
one               17      16      21
two               21      40      24


### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [51]:
date_range = pd.date_range(start="2021-01-01", end="2021-12-31", freq='D')
df = pd.DataFrame({'Date': np.random.choice(date_range, size=10), 'Category': np.random.choice(['A','B','C'], size=(10)), 'Value': np.random.randint(1,21, size=(10))})
print(df)

#Pivot Table: We perform data grouping and data aggregation, the result generated by grouping and aggregation is represented in tabular format i.e Pivot Table
pivot_table = pd.pivot_table(values='Value', index='Date', columns='Category', aggfunc='sum', data=df)
pivot_table

        Date Category  Value
0 2021-06-02        A      3
1 2021-06-26        A      2
2 2021-04-09        A     16
3 2021-09-11        A     12
4 2021-05-15        C     10
5 2021-08-25        B      8
6 2021-01-27        B     20
7 2021-01-30        A      7
8 2021-07-18        B     16
9 2021-10-04        C      9


Category       A     B     C
Date                        
2021-01-27   NaN  20.0   NaN
2021-01-30   7.0   NaN   NaN
2021-04-09  16.0   NaN   NaN
2021-05-15   NaN   NaN  10.0
2021-06-02   3.0   NaN   NaN
2021-06-26   2.0   NaN   NaN
2021-07-18   NaN  16.0   NaN
2021-08-25   NaN   8.0   NaN
2021-09-11  12.0   NaN   NaN
2021-10-04   NaN   NaN   9.0

2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

In [56]:
df = pd.DataFrame({'Year': np.random.choice(['2021','2022','2023','2024'], size=15), 'Quarter': np.random.choice(['Q1','Q2','Q3','Q4'], size=15), 'Revenue': np.random.randint(1,1000, size=15)})
print(df)

pivot_table = pd.pivot_table(values='Revenue', index='Year', columns='Quarter', aggfunc='mean', data=df)
pivot_table

    Year Quarter  Revenue
0   2024      Q3      537
1   2023      Q3      103
2   2024      Q1      777
3   2021      Q4       52
4   2022      Q2      171
5   2021      Q1      978
6   2022      Q1      308
7   2023      Q4      728
8   2021      Q3      890
9   2022      Q1      162
10  2023      Q1      100
11  2024      Q3      873
12  2021      Q2      187
13  2021      Q4      576
14  2022      Q1      451


Quarter     Q1     Q2     Q3     Q4
Year                               
2021     978.0  187.0  890.0  314.0
2022     307.0  171.0    NaN    NaN
2023     100.0    NaN  103.0  728.0
2024     777.0    NaN  705.0    NaN

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [65]:
df = pd.DataFrame(np.random.randint(1,11, size=(5,3)), columns=['A','B','C'])
print("The Original Dataframe is: ")
print(df)

new_df = df.apply(lambda x:x*2)
new_df

The Original Dataframe is: 
    A  B  C
0  10  2  8
1   8  1  3
2   2  8  7
3   3  5  4
4  10  4  8


A   B   C
0  20   4  16
1  16   2   6
2   4  16  14
3   6  10   8
4  20   8  16

2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.


In [73]:
df = pd.DataFrame(np.random.randint(1,21, size=(6,3)), columns=['A','B','C'])
print("The Original Dataframe is: ")
print(df)

#Performing the sum
df['Sum Each Row'] = df.apply(lambda row:row.sum(), axis=1)
df

The Original Dataframe is: 
    A   B   C
0  16  10  17
1  17  20   8
2  17   1  10
3   6   5  14
4  12   4   6
5  18   1  19


A   B   C  Sum Each Row
0  16  10  17            43
1  17  20   8            45
2  17   1  10            28
3   6   5  14            25
4  12   4   6            22
5  18   1  19            38

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.

In [ ]:
series = pd.Series(['subrat','raj','john','sagar','shiv'], index=['A','B','C','D','E'])
print("Original Series: ")
print(series)

new_series = series.str.upper() #.str consider the string and .upper() convert each index string value to uppercase and new_series is another series of string with uppercase values
print("New Series is: ")
print(new_series)

Original Series: 
A    subrat
B       raj
C      john
D     sagar
E      shiv
dtype: str
New Series is: 
A    SUBRAT
B       RAJ
C      JOHN
D     SAGAR
E      SHIV
dtype: str


2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [ ]:
series = pd.Series(['subrat','raj','john','sagar','shiv'], index=['A','B','C','D','E'])
print("Original Series: ")
print(series)

first_three_char = series.str[:3] #.str consider the string and [:3] tell to extract first 3 char of each index string i.e char at 0,1 and 2 indexes. first_three_char is another series of string with first 3 chars
print(first_three_char, type(first_three_char))

Original Series: 
A    subrat
B       raj
C      john
D     sagar
E      shiv
dtype: str
A    sub
B    raj
C    joh
D    sag
E    shi
dtype: str <class 'pandas.Series'>
